#!/bin/sh

echo "Running 'post-checkout' hook"

# Get the current branch name
branch_name=$(git branch | grep "*" | sed "s/\* //")
echo "branch: $branch_name"

# we should be in the root folder of the git repository
cd laravel

echo "<?php return ['string' => '$(git describe --tags --exact-match 2>/dev/null || git describe --tags)'];" > config/version.php

echo "Running 'composer install'"
composer install
# Run migrations
echo "Running database migrations..."
php artisan migrate --force
# Check for changes in config files
if git diff --name-only HEAD@{1} HEAD | grep -qE '^config/.*\.php'; then
	echo "Config changes detected. Recaching config..."
	php artisan config:cache
else
	echo "No config changes detected. Skipping config cache."
fi
# Check for changes in route files
if git diff --name-only HEAD@{1} HEAD | grep -qE '^route/.*\.php'; then
	echo "Route changes detected. Recaching route..."
	php artisan route:cache
else
	echo "No route changes detected. Skipping route cache."
fi
# Check for changes in view files
if git diff --name-only HEAD@{1} HEAD | grep -qE '^resources/views/.*\.php'; then
	echo "View changes detected. Recaching views..."
	php artisan route:cache
else
	echo "No view changes detected. Skipping view cache."
fi
# Check if event files changed in the merge
if git diff --name-only HEAD@{1} HEAD | grep -qE '^app/Events/.*\.php'; then
  echo "Event files changed. Caching events..."
  php artisan event:cache
else
  echo "No event file changes detected. Skipping event cache."
fi

echo "Running ./artisan storage:unlink && ./artisan storage:link"
./artisan storage:unlink && ./artisan storage:link

echo "Running 'npm install and npm run build'"
npm install && npm run build

echo "Restarting all queues with 'sudo supervisorctl restart all'"
sudo supervisorctl restart all

cd ..
