#!/bin/sh

echo "Running 'post-merge' hook"

# Get the current branch name
branch_name=$(git branch | grep "*" | sed "s/\* //")
echo "branch: $branch_name"

# we should be in the root folder of the git repository
echo "Running 'composer install'"
cd laravel && composer install && cd ..
echo "Running 'npm install and npm run build'"
cd laravel && npm install && npm run build && cd ..
