# https://github.com/tmux-python/tmuxp/issues/739
# https://tmuxp.git-pull.com/
#
# Set SONICOM_GIT_ROOT to the path to the isf-sonicom-laravel repository
#
#
session_name: sonicom
start_directory: "${SONICOM_GIT_ROOT}"
windows:
  - window_name: logs 
    layout: even-vertical
    suppress_history: false
    start_directory: "laravel/storage/logs"
    panes:
      - "tail -F laravel.log"
      - "tail -F reverb.log"
      - shell_command:
        - tmux set -w pane-border-status bottom
        - tmux select-pane -T laravel.log -t logs.0
        - tmux select-pane -T reverb.log -t logs.1
        - tmux select-pane -T worker.log -t logs.2
        - "tail -F worker.log"
  - window_name: git 
    suppress_history: false
    panes:
      - shell_command:
        - tmux set -w pane-border-status top
        - tmux select-pane -T git git.0
        - git status
  - window_name: services
    layout: even-vertical
    suppress_history: false
    panes:
      - sudo supervisorctl status
      - echo "If you need the npm dev server, then run 'cd laravel && npm run dev'"
  - window_name: storage
    layout: even-vertical
    suppress_history: false
    panes:
      - shell_command:
        - tmux set -w pane-border-status bottom
        - tmux select-pane -T public -t storage.0
        - cd laravel/storage/app/public
  - window_name: artisan 
    start_directory: "laravel"
    layout: even-vertical
    suppress_history: false
    panes:
      - shell_command:
        - tmux set -w pane-border-status bottom
        - tmux select-pane -T artisan -t artisan.0
  - window_name: octave 
    layout: even-vertical
    panes:
      - shell_command:
        - tmux select-pane -T octave -t octave.0
  - window_name: vi
    layout: even-vertical
    start_directory: laravel
    panes:
      - shell_command:
        - tmux select-pane -T vi -t vi.0
  - window_name: queue
    layout: even-vertical
    start_directory: "laravel"
    panes:
      - shell_command:
        - ./artisan queue:monitor default
